

POST https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
Authorization:
Content-Type: application/json

{
  "model": "deepseek-v3.2",
  "messages": [
    {
      "role": "user",
      "content": "写一个冒泡排序的java示例代码"
    }
  ],
  "stream": true,
  "stream_options": {
    "include_usage": true
  },
  "enable_thinking": false
}




